# Cấu hình phân trang
paginate: 8 # Số lượng bài viết hiển thị trên 1 trang (bạn có thể đổi thành 9, 12, v.v.)
paginate_path: "/page:num/"

# Cấu hình mặc định không dùng layout cho _posts
defaults:
  - scope:
      path: "_posts"
    values:
      layout: null
